version: '3'
services:
  front:
    image: msa-frontservice
    ports:
      - "8084:8084"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    depends_on:
      - kafka
  encryption:
    image: msa-encryptionservice
    ports:
      - "8085:8085"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    depends_on:
      - kafka
  stats:
    image: stats-service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
  kafka:
    image: vmykh/kafka-test
