version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:1, encryption_topic:1:1"
  front:
    build: ./msa-frontservice
    ports:
      - "8080:8080"
    links:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  encryption:
    build: ./msa-encryptionservice
    ports:
      - "8081:8081"
    links:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
